#!/bin/bash
set -eux
rm -rf datasette || true
mkdir datasette
cp combined.db datasette/
cp combined_filtered.db datasette/
cp datasette-src/* datasette/
cd datasette/
git init
git checkout -b main
git add .
git commit -a -m 'Generated by https://github.com/pwyf/pwyf-wee-scripts'
git update-server-info
