#!/bin/bash
set -eux
rm -rf datasette || true
mkdir datasette
mv iati_data.db datasette/
mv iati_data_filtered.db datasette/
mv crs_candid_cgap.db datasette/
mv combined.db datasette/
cp datasette-src/* datasette/
cd datasette/
git init
git checkout -b main
git add .
git commit -a -m 'Generated by https://github.com/pwyf/pwyf-wee-scripts'
git update-server-info
